name: sync

on:
  watch:
    types: started
  # schedule:
  #   - cron: '0 */4 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Sync Data
        env:
          TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
        run: |-
          sudo timedatectl set-timezone Asia/Shanghai
          yarn
          git submodule update --init --recursive
          cd sync && yarn && cd ..
          yarn sync
      - name: Generate Static
        run: |-
          yarn generate
          cd dist/
          git init
          git remote add origin git@github.com:willin-love/willin-love.github.io.git
          git config --global user.email "bot@github.com" && git config --global user.name "Bot"
          git add . && git commit -m ":memo: Thanks for $GITHUB_ACTOR's star" || exit 0
          git push -f origin master
