name: sync

on:
  watch:
    types: started
  # schedule:
  #   - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Fetch events
        run: |-
          sudo timedatectl set-timezone Asia/Shanghai
          npm install
          git submodule update --init --recursive
          cd sync && npm install && cd ..
          npm run sync
      - name: Commit and push
        run: |-
          git config --global user.email "bot@github.com" && git config --global user.name "Bot"
          git add . && git commit -m ":memo: 感谢 $GITHUB_ACTOR 的关注，触发了更新" || exit 0
          git push
